input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  mutate {
    remove_field => ["@version", "host", "port"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "springboot-logs"
  }
  stdout { codec => rubydebug }
}
