apiVersion: v1
kind: Pod
metadata:
  name: productapp-pod
  labels:
    app: productapp
spec:
  containers:
  - name: productapp
    image: rgupta00/productapp:1.1
    ports:
    - containerPort: 8090