bank.name=state bank of india qa profile
bank.branch=indore qa profile
bank.location=indore qa profile
bank.address=indore qa profile
bank.phone=9876543200
bank.email=indore@bankapp.com qa profile
spring.config.activate.on-profile=qa
