bank.name=state bank of india test profile
bank.branch=indore test profile
bank.location=indore test profile
bank.address=indore test profile
bank.phone=9876543200
bank.email=indore@bankapp.com test profile
