apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: productapp-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: productapp
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s