apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapp-deploy
  annotations:
    kubernetes.io/change-cause: "deploy productapp v1.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productapp
  template:
    metadata:
      labels:
        app: productapp
    spec:
      containers:
      - name: productapp
        image: rgupta00/productapp:1.1

        ports:
        - containerPort: 8090

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: productapp
spec:
  selector:
    app: productapp

  ports:
  - port: 8090
    targetPort: 8090

  type: NodePort