apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-config

data:
  CARDS_SERVICE_URL: "http://cards:9090"
  LOANS_SERVICE_URL: "http://loans:8090"

  INFO_MESSAGE: "Welcome to Accounts Application from Kubernetes ConfigMap"
  INFO_NAME: "Raj Gupta - Kubernetes Workshop"