apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gateway

  template:
    metadata:
      labels:
        app: gateway

    spec:
      containers:
        - name: gateway
          image: rgupta00/gateway:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 8072

          envFrom:
            - configMapRef:
                name: gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway

spec:
  type: NodePort

  selector:
    app: gateway

  ports:
    - port: 8072
      targetPort: 8072
      nodePort: 30004