spring.application.name=bankapp
server.port=8090
server.servlet.context-path=/bankapp
#configration for mysql database
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


